service: filmdatabase

custom:
  settings:
    CINEMAWORLD_TABLE: CinemaWorld
    FILMWORLD_TABLE: FilmWorld

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  environment:
    CINEMAWORLD_TABLE: { "Ref": "Cinemaworld" }
    FILMWORLD_TABLE: { "Ref": "Filmworld" }
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.CINEMAWORLD_TABLE}"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.FILMWORLD_TABLE}"

functions:
  createFilm:
    handler: handler.createFilm
    events:
      - http:
          path: /{database}/movie
          method: post
          cors: true

  getAllFilms:
    handler: handler.getAllFilms
    events:
      - http:
          path: /{database}/movies
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  getFilms:
    handler: handler.getFilms
    events:
      - http:
          path: /{database}/movies/{number}
          method: get
          cors: true

  getFilm:
    handler: handler.getFilm
    events:
      - http:
          path: /{database}/movie/{id}
          method: get
          cors: true

  updateFilm:
    handler: handler.updateFilm
    events:
      - http:
          path: /{database}/movie/{id}
          method: put
          cors: true

  deleteFilm:
    handler: handler.deleteFilm
    events:
      - http:
          path: /{database}/movie/{id}
          method: delete
          cors: true
  csvExport:
    handler: handler.csvExport
    events:
      - sqs: arn:aws:sqs:ap-southeast-2:939450071149:CsvTransactionQueue

resources:
  Resources:
    Cinemaworld:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.CINEMAWORLD_TABLE}
    Filmworld:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.FILMWORLD_TABLE}
